#!/bin/bash
${cor[3]}#!/bin/bash
source cabecalho
[[ -e /etc/bash.bashrc-bakup ]] && _autorun="\033[1;32m[ACTIVADO]" || _autorun="\033[1;31m[DESACTIVADO]"
echo -e "${cor[1]} =================================== ${cor[0]}"
echo -e "${cor[2]} ∆ ${cor[5]} ${txt[4]}"
echo -e "${cor[1]} =================================== ${cor[0]}"
echo -e "${cor[2]}[${cor[1]}00${cor[2]}] ${cor[5]} ${txt[13]}"
echo -e "${cor[2]}[${cor[1]}01${cor[2]}] ${cor[3]} ${txt[5]}"
echo -e "${cor[2]}[${cor[1]}02${cor[2]}] ${cor[3]} ${txt[6]}"
echo -e "${cor[2]}[${cor[1]}03${cor[2]}] \033[1;32m ${txt[7]}"
echo -e "${cor[2]}[${cor[1]}04${cor[2]}] \033[1;31m ${txt[8]}"
echo -e "${cor[2]}[${cor[1]}05${cor[2]}] ${cor[3]} ${txt[12]}"
echo -e "${cor[2]}[${cor[1]}05${cor[2]}] ${cor[3]} ${txt[20]} $VERIFICAR_PID"
echo -e "${cor[2]}[${cor[1]}07${cor[2]}] ${cor[3]} ${txt[26]}"
echo -e "${cor[2]}[${cor[1]}08${cor[2]}] ${cor[3]} ${txt[322]} $_autorun"
echo -e "${cor[2]}[${cor[1]}09${cor[2]}] ${cor[3]} ${txt[256]}"
echo -e "${cor[2]}[${cor[1]}10${cor[2]}] ${cor[3]} ${txt[337]}"
echo -e "${cor[1]} =================================== ${cor[0]}"
